# Generated by Django 5.0 on 2023-12-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bde",
            name="interview_schedule",
            field=models.DateField(max_length=50),
        ),
    ]
