# Generated by Django 4.2.7 on 2023-12-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_bde_candidate_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bde",
            old_name="candidate_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="bde",
            name="interview_schedule_date",
        ),
        migrations.RemoveField(
            model_name="bde",
            name="scheduled_by",
        ),
    ]
