# Generated by Django 4.2.7 on 2023-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_rename_candidate_name_bde_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DEVELOPER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("developer_name", models.CharField(max_length=100)),
            ],
        ),
    ]
