# Generated by Django 4.2.7 on 2023-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_developer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=150)),
            ],
        ),
    ]
