# Generated by Django 4.2.7 on 2023-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("question", models.TextField(max_length=200)),
                ("answer", models.TextField(max_length=500)),
                ("technology", models.CharField(max_length=20)),
                ("question_level", models.CharField(max_length=50)),
            ],
        ),
    ]
