# Generated by Django 4.2.7 on 2023-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=20)),
                ("scheduled_by", models.CharField(max_length=20)),
                ("interview_mode", models.CharField(max_length=20)),
                ("technology", models.CharField(max_length=20)),
                ("Interview_rounds", models.IntegerField()),
                ("interviewer_name", models.CharField(max_length=20)),
                ("candidate_name", models.CharField(max_length=100)),
                ("interview_type", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("job_title", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=30)),
            ],
        ),
    ]
