# Generated by Django 4.2.7 on 2023-12-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="interview",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
