# Generated by Django 4.2.7 on 2023-12-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_alter_interview_created_date_alter_interview_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="company_name",
            field=models.ForeignKey(
                max_length=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.company",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interviewer_name",
            field=models.ForeignKey(
                max_length=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.developer",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="scheduled_by",
            field=models.ForeignKey(
                max_length=20,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.bde",
            ),
        ),
    ]
